[project]
name = "persian-crito-aligmment"
version = "0.1.0"
description = "Reader for Farnoosh Shamsian's Persian Crito Alignment"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ryland>=0.13.0",
]
